test:
	g++ zeta0/test.cpp -o zeta0/test
	g++ mach0/test.cpp -o mach0/test
	zeta0/test 100
	mach0/test 100

utest:
	g++ zeta0/utest.cpp -o zeta0/utest
	g++ mach0/utest.cpp -o mach0/utest
	zeta0/utest
	mach0/utest

vtest:
	g++ zeta0/vtest.cpp -o zeta0/vtest
	g++ mach0/vtest.cpp -o mach0/vtest
	zeta0/vtest
	mach0/vtest
